# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.recipe_service_pb2 as recipe__service__pb2


class RecipeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecipe = channel.unary_unary(
        '/recipe.RecipeService/GetRecipe',
        request_serializer=recipe__service__pb2.GetRecipeRequest.SerializeToString,
        response_deserializer=recipe__service__pb2.GetRecipeResponse.FromString,
        )
    self.CreateRecipe = channel.unary_unary(
        '/recipe.RecipeService/CreateRecipe',
        request_serializer=recipe__service__pb2.CreateRecipeRequest.SerializeToString,
        response_deserializer=recipe__service__pb2.CreateRecipeResponse.FromString,
        )


class RecipeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRecipe(self, request, context):
    """Get single recipe by id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateRecipe(self, request, context):
    """Create new recipe
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecipeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecipe': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecipe,
          request_deserializer=recipe__service__pb2.GetRecipeRequest.FromString,
          response_serializer=recipe__service__pb2.GetRecipeResponse.SerializeToString,
      ),
      'CreateRecipe': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecipe,
          request_deserializer=recipe__service__pb2.CreateRecipeRequest.FromString,
          response_serializer=recipe__service__pb2.CreateRecipeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'recipe.RecipeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
