# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipe_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recipe_service.proto',
  package='recipe',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14recipe_service.proto\x12\x06recipe\"\x1e\n\x10GetRecipeRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x11GetRecipeResponse\x12\x1e\n\x06recipe\x18\x01 \x01(\x0b\x32\x0e.recipe.Recipe\"5\n\x13\x43reateRecipeRequest\x12\x1e\n\x06recipe\x18\x01 \x01(\x0b\x32\x0e.recipe.Recipe\"\x16\n\x14\x43reateRecipeResponse\"7\n\x06Recipe\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2\xa0\x01\n\rRecipeService\x12\x42\n\tGetRecipe\x12\x18.recipe.GetRecipeRequest\x1a\x19.recipe.GetRecipeResponse\"\x00\x12K\n\x0c\x43reateRecipe\x12\x1b.recipe.CreateRecipeRequest\x1a\x1c.recipe.CreateRecipeResponse\"\x00\x62\x06proto3')
)




_GETRECIPEREQUEST = _descriptor.Descriptor(
  name='GetRecipeRequest',
  full_name='recipe.GetRecipeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='recipe.GetRecipeRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_GETRECIPERESPONSE = _descriptor.Descriptor(
  name='GetRecipeResponse',
  full_name='recipe.GetRecipeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipe', full_name='recipe.GetRecipeResponse.recipe', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=115,
)


_CREATERECIPEREQUEST = _descriptor.Descriptor(
  name='CreateRecipeRequest',
  full_name='recipe.CreateRecipeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipe', full_name='recipe.CreateRecipeRequest.recipe', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=170,
)


_CREATERECIPERESPONSE = _descriptor.Descriptor(
  name='CreateRecipeResponse',
  full_name='recipe.CreateRecipeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=194,
)


_RECIPE = _descriptor.Descriptor(
  name='Recipe',
  full_name='recipe.Recipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='recipe.Recipe.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='recipe.Recipe.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='recipe.Recipe.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=251,
)

_GETRECIPERESPONSE.fields_by_name['recipe'].message_type = _RECIPE
_CREATERECIPEREQUEST.fields_by_name['recipe'].message_type = _RECIPE
DESCRIPTOR.message_types_by_name['GetRecipeRequest'] = _GETRECIPEREQUEST
DESCRIPTOR.message_types_by_name['GetRecipeResponse'] = _GETRECIPERESPONSE
DESCRIPTOR.message_types_by_name['CreateRecipeRequest'] = _CREATERECIPEREQUEST
DESCRIPTOR.message_types_by_name['CreateRecipeResponse'] = _CREATERECIPERESPONSE
DESCRIPTOR.message_types_by_name['Recipe'] = _RECIPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRecipeRequest = _reflection.GeneratedProtocolMessageType('GetRecipeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECIPEREQUEST,
  __module__ = 'recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:recipe.GetRecipeRequest)
  ))
_sym_db.RegisterMessage(GetRecipeRequest)

GetRecipeResponse = _reflection.GeneratedProtocolMessageType('GetRecipeResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRECIPERESPONSE,
  __module__ = 'recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:recipe.GetRecipeResponse)
  ))
_sym_db.RegisterMessage(GetRecipeResponse)

CreateRecipeRequest = _reflection.GeneratedProtocolMessageType('CreateRecipeRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATERECIPEREQUEST,
  __module__ = 'recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:recipe.CreateRecipeRequest)
  ))
_sym_db.RegisterMessage(CreateRecipeRequest)

CreateRecipeResponse = _reflection.GeneratedProtocolMessageType('CreateRecipeResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATERECIPERESPONSE,
  __module__ = 'recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:recipe.CreateRecipeResponse)
  ))
_sym_db.RegisterMessage(CreateRecipeResponse)

Recipe = _reflection.GeneratedProtocolMessageType('Recipe', (_message.Message,), dict(
  DESCRIPTOR = _RECIPE,
  __module__ = 'recipe_service_pb2'
  # @@protoc_insertion_point(class_scope:recipe.Recipe)
  ))
_sym_db.RegisterMessage(Recipe)



_RECIPESERVICE = _descriptor.ServiceDescriptor(
  name='RecipeService',
  full_name='recipe.RecipeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=254,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecipe',
    full_name='recipe.RecipeService.GetRecipe',
    index=0,
    containing_service=None,
    input_type=_GETRECIPEREQUEST,
    output_type=_GETRECIPERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateRecipe',
    full_name='recipe.RecipeService.CreateRecipe',
    index=1,
    containing_service=None,
    input_type=_CREATERECIPEREQUEST,
    output_type=_CREATERECIPERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECIPESERVICE)

DESCRIPTOR.services_by_name['RecipeService'] = _RECIPESERVICE

# @@protoc_insertion_point(module_scope)
